# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-11-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='存放編號')),
                ('pro_id', models.CharField(max_length=32, verbose_name='商品正編product_id')),
                ('title', models.CharField(max_length=32, verbose_name='商品名稱')),
                ('id_num', models.CharField(max_length=32, verbose_name='商品編號')),
                ('buy_amount', models.IntegerField(verbose_name='預計購買數量')),
                ('price', models.CharField(max_length=11, verbose_name='price')),
                ('sort', models.EmailField(max_length=32, verbose_name='類別')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'paycar',
            },
        ),
    ]
